#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/Network/Abstraction
.build/debug/Tests/Network/Address
.build/debug/Tests/Network/Client
.build/debug/Tests/Network/DNS
.build/debug/Tests/Network/DNSMessage
.build/debug/Tests/Network/IP
.build/debug/Tests/Network/NetworkStream
.build/debug/Tests/Network/Options
.build/debug/Tests/Network/Server
.build/debug/Tests/Network/Socket
.build/debug/Tests/Network/SystemLogger
